#!/bin/bash
# Show Clawdbot documentation sitemap by category

DOCS_URL="https://docs.clawd.bot"

echo "Clawdbot Documentation Sitemap"
echo "=============================="
echo ""
echo "Getting Started (/start/)"
echo "  - getting-started"
echo "  - setup"
echo "  - faq"
echo "  - wizard"
echo ""
echo "Gateway & Operations (/gateway/)"
echo "  - configuration"
echo "  - configuration-examples"
echo "  - security"
echo "  - health"
echo "  - logging"
echo "  - tailscale"
echo "  - troubleshooting"
echo ""
echo "Providers (/providers/)"
echo "  - discord"
echo "  - telegram"
echo "  - whatsapp"
echo "  - slack"
echo "  - signal"
echo "  - imessage"
echo "  - msteams"
echo "  - matrix"
echo "  - nostr"
echo "  - troubleshooting"
echo ""
echo "Core Concepts (/concepts/)"
echo "  - agent"
echo "  - sessions"
echo "  - messages"
echo "  - models"
echo "  - queues"
echo "  - streaming"
echo "  - system-prompt"
echo ""
echo "Tools (/tools/)"
echo "  - bash"
echo "  - browser"
echo "  - skills"
echo "  - reactions"
echo "  - subagents"
echo "  - thinking"
echo "  - browser-linux-troubleshooting"
echo ""
echo "Automation (/automation/)"
echo "  - cron-jobs"
echo "  - webhook"
echo "  - polling"
echo "  - gmail-pubsub"
echo ""
echo "CLI (/cli/)"
echo "  - gateway"
echo "  - message"
echo "  - sandbox"
echo "  - update"
echo ""
echo "Platforms (/platforms/)"
echo "  - macos"
echo "  - linux"
echo "  - windows"
echo "  - ios"
echo "  - android"
echo "  - hetzner"
echo ""
echo "Install (/install/)"
echo "  - docker"
echo "  - ansible"
echo "  - bun"
echo "  - nix"
echo "  - updating"
echo ""
echo "Reference (/reference/)"
echo "  - templates"
echo "  - rpc"
echo "  - device-models"
echo ""
echo "Base URL: $DOCS_URL"
